FROM dart:stable
WORKDIR /app
COPY pubspec.yaml pubspec.lock analysis_options.yaml ./
COPY lib lib
COPY tool tool
RUN dart pub get
ENV GROK_PROXY_PORT=8080
ENV GROK_PROXY_BIND=0.0.0.0
EXPOSE 8080
CMD ["dart", "run", "tool/grok_proxy.dart"]