# Interactive setup - paste your keys when prompted.
# Run: powershell -ExecutionPolicy Bypass -File .\scripts\setup_grok_credentials.ps1

$ErrorActionPreference = 'Stop'
$Root = Split-Path $PSScriptRoot -Parent
$envFile = Join-Path $Root 'grok_proxy.local.env'

Write-Host ''
Write-Host 'Evolve Grok - real mode setup' -ForegroundColor Cyan
Write-Host 'Get X Client ID: https://developer.x.com/' -ForegroundColor DarkGray
Write-Host 'Callback URL to register: http://127.0.0.1:8787/auth/callback' -ForegroundColor DarkGray
Write-Host 'Get xAI API key (optional): https://console.x.ai/' -ForegroundColor DarkGray
Write-Host ''

$clientId = Read-Host 'X_CLIENT_ID (required)'
if (-not $clientId -or $clientId.Trim().Length -lt 8) {
    Write-Host 'Client ID too short or empty - cancelled.' -ForegroundColor Red
    exit 1
}

$clientSecret = Read-Host 'X_CLIENT_SECRET (optional, press Enter to skip)'
$xaiKey = Read-Host 'XAI_API_KEY (optional, press Enter to skip)'

$lines = @(
    '# Auto-generated by setup_grok_credentials.ps1',
    '# X Developer redirect URI: http://127.0.0.1:8787/auth/callback',
    '',
    "X_CLIENT_ID=$($clientId.Trim())",
    "X_CLIENT_SECRET=$($clientSecret.Trim())",
    "XAI_API_KEY=$($xaiKey.Trim())",
    '',
    '# Do NOT set GROK_PROXY_MOCK=1 for real X login.'
)
Set-Content -Path $envFile -Value $lines -Encoding UTF8
Write-Host ''
Write-Host "Saved $envFile" -ForegroundColor Green
Write-Host 'Starting real-mode proxy...' -ForegroundColor Cyan
Write-Host ''

& "$PSScriptRoot\activate_real_grok.ps1"