#!/usr/bin/env python3
"""Per-key wallet UI translations for fr, de, pt, ar, zh, hi, ja + es supplement."""
from __future__ import annotations

# fmt: off
# ruff: noqa: E501

ES_SUPPLEMENT: dict[str, str] = {
    "wallet_dapp_send_receive": "Enviar / Recibir",
    "wallet_dapp_send_receive_note": "Todo monedero registrado puede recibir PERC. Envíe solo a una dirección PERC.",
    "wallet_err_minimum_send": "El envío mínimo es {min} {symbol} (1 cent)",
    "wallet_err_sign_in_to_send": "Inicie sesión para enviar {name}",
    "wallet_login_language_label": "Idioma",
    "wallet_mesh_connected": "Conectado a {count} otro(s) monedero(s) en la cadena Perccent compartida",
    "wallet_mesh_incomplete": "Vinculando monederos en la malla…",
    "wallet_mesh_network_synced": "Semilla conectada — altura de internet {height} — nodo {node}",
    "wallet_mesh_network_syncing": "Sincronizando con la altura de bloque de internet {height}…",
    "wallet_mesh_peers": "Pares: {peers}",
    "wallet_mesh_title": "Malla concurrente de monederos",
    "wallet_opening_error": "No se pudo abrir el monedero. Compruebe su conexión e inténtelo de nuevo.",
    "wallet_opening_message": "Su monedero Perccent se está cargando. Espere…",
    "wallet_opening_retry": "Reintentar",
    "wallet_opening_title": "Abriendo monedero",
    "wallet_password_mismatch": "Las contraseñas no coinciden",
    "wallet_inbound_revert_days": "7 dias",
    "wallet_inbound_revert_hours": "varias horas",
    "wallet_inbound_revert_seconds": "poco tiempo",
    "wallet_send_amount_hint": "0.00000001",
    "wallet_status_account_created": "Cuenta creada",
    "wallet_status_faucet_credited": "+{amount} {symbol}",
    "wallet_status_genesis_renewal": (
        "Bloque génesis — ciclo de tesorería {cycle} renovado "
        "(283M {symbol} {name})"
    ),
    "wallet_status_sent_instant": (
        "Enviado {amount} {symbol} a {dest} (comisión de red {fee} {symbol})"
    ),
    "wallet_status_sent_queued": (
        "Enviado {amount} {symbol} a {dest} (comisión de red {fee} {symbol}) — "
        "en cola hasta que inicien sesión en la red en {delay}; si no, vuelve a su monedero"
    ),
    "wallet_status_signed_in": "Sesión iniciada como {user}",
    "wallet_status_treasury_cap": "Límite de tesorería alcanzado",
    "wallet_status_treasury_empty": "Tesorería vacía — ejecute otro escenario más tarde",
    "wallet_status_treasury_secured": (
        "Tesorería asegurada — en espera del inicio de sesión de tesorería "
        "semilla para lanzar la cadena"
    ),
    "wallet_sync_button": "Sincronizar monedero",
    "wallet_sync_partial": "Sincronización parcial — altura local {local}, altura de red {network}",
    "wallet_sync_seed_offline": "No se puede alcanzar el nodo semilla — compruebe su conexión a internet e inténtelo de nuevo",
    "wallet_sync_success": "Monedero sincronizado con la semilla — altura de bloque {height}",
    "wallet_sync_syncing": "Sincronizando…",
    "ward_voting_login_required": "Inicie sesión para enviar una propuesta o emitir su voto. Los resultados en vivo son públicos — no hace falta votar para verlos.",
}


def _fr() -> dict[str, str]:
    return {
        "splash_enter_app": "Entrer dans Evolve",
        "splash_preparing_wallet": "Préparation du portefeuille…",
        "splash_signed_in_as": "Connecté en tant que {user}",
        "splash_version_checking": "Recherche de mises à jour…",
        "splash_version_latest": "Vous avez la dernière version ({version})",
        "splash_version_update": "Mise à jour disponible : {latest} — vous avez {current}",
        "splash_version_update_action": "Obtenir la mise à jour",
        "wallet_address_copied": "Adresse copiée",
        "wallet_address_label": "Votre adresse Perccent",
        "wallet_app_gate_note": "Evolve se déverrouille après inscription et réception d'une adresse Perccent sur cet appareil.",
        "wallet_app_gate_title": "Créez d'abord votre portefeuille",
        "wallet_avg_block_time": "Temps moyen par bloc : {time}",
        "wallet_back_to_sign_in": "Retour à la connexion",
        "wallet_balance_label": "Solde disponible",
        "wallet_block_height": "Hauteur de bloc : {height}",
        "wallet_blockchain_awaiting_launch": "La blockchain attend la connexion rgsnedds sur l'onglet trésorerie seed pour le lancement.",
        "wallet_blockchain_launch_body": "Trésorier connecté — la chaîne Perccent est active. Lancez des scénarios pour avancer les blocs.",
        "wallet_blockchain_launch_ok": "C'est parti",
        "wallet_blockchain_launch_title": "Blockchain lancée !",
        "wallet_burned_note": "Chaque frais d'envoi réseau (0,00000001 PERC) est définitivement brûlé — retiré de la circulation sur la chaîne Perccent.",
        "wallet_burned_title": "PERC brûlés",
        "wallet_burned_total": "Total brûlé cumulé : {amount} PERC",
        "wallet_camera_permission_allow": "Autoriser la caméra",
        "wallet_camera_permission_body": "Evolve a besoin de votre caméra pour scanner le QR de réception PERC d'un autre utilisateur lors d'un envoi Perccent.",
        "wallet_camera_permission_denied": "Accès caméra refusé — autorisez la caméra dans les réglages pour scanner les QR PERC.",
        "wallet_camera_permission_not_now": "Pas maintenant",
        "wallet_camera_permission_open_settings": "Ouvrir les réglages",
        "wallet_camera_permission_settings_body": "L'accès caméra est désactivé pour Evolve. Ouvrez les réglages et activez Caméra pour scanner les QR PERC.",
        "wallet_camera_permission_title": "Autoriser l'accès à la caméra",
        "wallet_choose_username": "Choisir un nom d'utilisateur",
        "wallet_chronoflux_graph_empty": "Lancez une analyse de probabilité % ou de cohésion sociale pour remplir les graphiques de variables Chronoflux.",
        "wallet_chronoflux_graph_note": "Radar pentagonal et séries temporelles à cinq points pour ρt, ω, σ, Iτ, Jμ — les temps suivent l'ordre des entrées Chronoflux selon les tirages de scénario.",
        "wallet_chronoflux_graph_title": "Variables Chronoflux à cinq points",
        "wallet_cooldown_popup_body": "Votre portefeuille a déjà puisé à la trésorerie dans les 7 dernières minutes. La chaîne Perccent avance sur les scénarios — votre prochain tirage (et bloc) éligible est dans environ {blockWait}. Vous pourrez de nouveau tirer xx/100 PERC après {wait}.",
        "wallet_cooldown_popup_ok": "OK",
        "wallet_cooldown_popup_title": "Tirage trésorerie en attente",
        "wallet_copy_address": "Copier l'adresse",
        "wallet_create_password": "Créer un mot de passe",
        "wallet_creator_credit": "Créé par rgsneddon · utilisant Grok · Roy D Herbert (Chronoflux Principia) · Valdok · Beam CTO Alex Romanov — fork Perccent confidentialité Beam",
        "wallet_dapp_analysis": "Galerie d'analyses",
        "wallet_dapp_bridge": "Pont side chain",
        "wallet_dapp_bridge_note": "Les microblocs de la side chain Chronoflux scellent en blocs main-chain à 100M.",
        "wallet_dapp_featured_label": "DAPP PRINCIPALE · v2.0",
        "wallet_dapp_governance": "Gouvernance Perccent",
        "wallet_dapp_main_chain": "Chaîne principale",
        "wallet_dapp_mesh": "Ponts mesh portefeuille",
        "wallet_dapp_mesh_peer": "Pont mesh concurrent — actif",
        "wallet_dapp_minter": "Émetteur d'actifs",
        "wallet_dapp_names": "Service de noms Perccent",
        "wallet_dapp_send_receive": "Envoyer / Recevoir",
        "wallet_dapp_send_receive_note": "Chaque portefeuille enregistré peut recevoir du PERC. Envoyez uniquement vers une adresse PERC.",
        "wallet_dapp_side_chain": "Side chain Chronoflux",
        "wallet_dapp_suite_subtitle": "Structure suite Beam — side chain, envoi/réception, ponts et gouvernance pour tous les utilisateurs",
        "wallet_dapp_suite_title": "Suite dapp Perccent",
        "wallet_dapp_ward_voting": "Vote de quartier communautaire",
        "wallet_details_section": "Détails chaîne et réseau",
        "wallet_evolution_app": "Version de l'app : {version}",
        "wallet_evolution_chain": "Chaîne évolutive : {id}",
        "wallet_evolution_epochs": "Époques d'évolution : {count}",
        "wallet_evolution_note": "Chaque version de l'app se connecte à la même chaîne — évolution vérifiée par la Chronoflux Principia.",
        "wallet_evolution_principia": "Chronoflux Principia : {id}",
        "wallet_evolution_title": "Blockchain évolutive",
        "wallet_evolution_versions": "Versions connectées : {versions}",
        "wallet_explorer_block_current": "Bloc n°{height}",
        "wallet_explorer_block_label": "Bloc actuel",
        "wallet_explorer_confirmations": "{count} confirmation(s) requise(s) — entièrement confirmé",
        "wallet_explorer_confirmed": "Entièrement confirmé (1 bloc)",
        "wallet_explorer_cumulative_chart": "Trésorerie cumulée émise",
        "wallet_explorer_degenerate_body": "Le même vecteur ne peut pas définir le cadre et fournir la dérive spatiale. La dérive est projetée lorsque le projecteur est construit à partir de la direction qu'il teste.",
        "wallet_explorer_degenerate_title": "Ansatz dégénéré à un vecteur — représentation frame-flow non admissible",
        "wallet_explorer_emission_chart": "Émission trésorerie par bloc",
        "wallet_explorer_empty": "Pas encore de blocs — lancez un scénario pour faire avancer la chaîne.",
        "wallet_explorer_frame_flow_center": "Scission frame-flow licite — le cadre définit la tranche ; la dérive reste dans la tranche",
        "wallet_explorer_frame_flow_status": "Statut A2 : scission frame-flow licite ; projecteur construit uniquement à partir du cadre ; dérive mesurable. Conséquence structurelle du régime de continuité fondateur.",
        "wallet_explorer_frame_flow_subtitle": "Ansatz dégénéré à un vecteur écarté ; scission de continuité licite conservée — microblocs regroupés en wards de {bundle}.",
        "wallet_explorer_frame_flow_title": "Scission Frame-Flow licite — 10 000 blocs Ward",
        "wallet_explorer_genesis_renewal": "Renouvellement genèse — cycle n°{cycle} (283M PERC Perccent)",
        "wallet_explorer_history": "HISTORIQUE DES BLOCS",
        "wallet_explorer_label_drift": "Dérive spatiale vμ dans la tranche",
        "wallet_explorer_label_frame": "Normale de cadre nμ définit la découpe",
        "wallet_explorer_label_projector": "Projecteur h(n)μν à partir du cadre",
        "wallet_explorer_label_split": "Scission nμ vμ = 0 orthogonale",
        "wallet_explorer_lawful_title": "Variables licites",
        "wallet_explorer_legend_emission": "Trésorerie Perccent (PERC)",
        "wallet_explorer_legend_txs": "Transactions",
        "wallet_explorer_link": "l'explorateur blockchain",
        "wallet_explorer_microblock_fair_usage": "Usage équitable de l'app",
        "wallet_explorer_microblock_height": "Microblocs d'usage équitable enregistrés : {count}",
        "wallet_explorer_microblock_log_count": "Entrées du journal : {count}",
        "wallet_explorer_microblock_log_empty": "Pas encore de microblocs — saisissez dans les champs d'analyse après le lancement de la blockchain.",
        "wallet_explorer_microblock_log_entry": "#{index} ward {ward} · μ{pos} · {time} · {label}{extra}",
        "wallet_explorer_microblock_log_note": "Chaque microbloc enregistre une interaction équitable — frappes et modifications des champs du formulaire d'analyse.",
        "wallet_explorer_microblock_log_title": "Journal des microblocs d'usage équitable",
        "wallet_explorer_microblock_log_truncated": "Affichage des {shown} derniers sur {total} microblocs enregistrés",
        "wallet_explorer_shard_count": "{visible} / {visible} wards sur le terrain — {lit} regroupés dans le cycle de scellement actuel",
        "wallet_explorer_subtitle": "Dapp chaîne Perccent basée sur graphe",
        "wallet_explorer_title": "l'explorateur blockchain",
        "wallet_explorer_trigger": "Déclenché par {user}",
        "wallet_explorer_tx_count": "{count} transaction(s)",
        "wallet_explorer_ward_cycle": "Cycle actuel : {completed} / {total} wards regroupés — ward n°{ward} en cours ({pending} / {bundle} microblocs)",
        "wallet_explorer_ward_field_count": "{wards} wards sur le terrain — {lit} regroupés ({bundle} microblocs chacun)",
        "wallet_explorer_ward_legend": "Vert = ward scellé · Bleu = ward en cours · Sombre = en attente",
        "wallet_explorer_ward_lifetime": "Wards scellés à vie : {count}",
        "wallet_explorer_ward_pending": "Ward actif n°{ward} : {pending} / {bundle} microblocs",
        "wallet_explorer_ward_seal_progress": "Cycle de scellement : {completed} / {total} wards-blocs — remplissage ward {pending} / {bundle} microblocs",
        "wallet_explorer_ward_subtitle": "Chaque ward scelle {bundle} microblocs Chronoflux. 10 000 wards complètent un cycle de scellement main-chain.",
        "wallet_explorer_ward_title": "Lots ward — explorateur dynamique de microblocs",
        "wallet_faucet_base": "Récompense de base",
        "wallet_faucet_bonus": "Bonus de résultat",
        "wallet_faucet_cooldown": "Prochain tirage trésorerie dans environ {wait}",
        "wallet_faucet_note": "Appuyez sur Calculer probabilité % ou Calculer cohésion sociale pour tirer xx/100 PERC de la trésorerie — xx est le résultat à deux chiffres (% ou SCS) — une fois toutes les 7 minutes.",
        "wallet_faucet_outcome": "Récompense de résultat",
        "wallet_faucet_title": "Robinet d'analyse",
        "wallet_faucet_total": "Total crédité",
        "wallet_login_note": "Connectez-vous avec le nom d'utilisateur choisi lors de la création de votre portefeuille.",
        "wallet_login_title": "Connexion Evolve Wallet",
        "wallet_logout": "Se déconnecter",
        "wallet_mesh_connected": "Connecté à {count} autre(s) portefeuille(s) sur la chaîne Perccent partagée",
        "wallet_mesh_incomplete": "Liaison des portefeuilles en mesh…",
        "wallet_mesh_network_synced": "Seed connecté — hauteur internet {height} — nœud {node}",
        "wallet_mesh_network_syncing": "Synchronisation vers la hauteur de bloc internet {height}…",
        "wallet_mesh_peers": "Pairs : {peers}",
        "wallet_mesh_title": "Mesh portefeuille concurrent",
        "wallet_opening_error": "Le portefeuille n'a pas pu s'ouvrir. Vérifiez votre connexion et réessayez.",
        "wallet_opening_message": "Votre portefeuille Perccent se charge. Veuillez patienter…",
        "wallet_opening_retry": "Réessayer",
        "wallet_opening_title": "Ouverture du portefeuille",
        "wallet_password": "Mot de passe",
        "wallet_password_confirm": "Confirmer le mot de passe",
        "wallet_privacy_note": "Perccent est dérivé de la confidentialité Beam — adresses confidentielles et soldes protégés sur l'appareil.",
        "wallet_privacy_title": "Perccent confidentiel Beam",
        "wallet_receive": "Recevoir",
        "wallet_receive_note": "D'autres peuvent scanner ce QR ou copier votre adresse PERC pour vous envoyer du Perccent (PERC).",
        "wallet_receive_qr_hint": "Scanner pour envoyer du PERC",
        "wallet_receive_title": "Recevoir Perccent",
        "wallet_register": "Créer un compte",
        "wallet_register_note": "Choisissez un nom d'utilisateur et un mot de passe — votre adresse Perccent est générée sur cet appareil.",
        "wallet_register_title": "Créer votre portefeuille",
        "wallet_scenario_block_capped": "Plafond de bloc scénario atteint ({max} vérifications)",
        "wallet_scenario_block_height": "Votre bloc scénario : {current} / {max}",
        "wallet_seed_block_anchor": "Ancre seed : bloc {block}",
        "wallet_send": "Envoyer",
        "wallet_send_address_pick": "Ou choisir une adresse connue",
        "wallet_send_amount": "Montant (PERC)",
        "wallet_send_amount_helper": "Divisible jusqu'à 0,00000001 PERC (1 cent). Tous les portefeuilles peuvent recevoir tout montant jusqu'à 1 cent.",
        "wallet_send_amount_hint": "0.00000001",
        "wallet_send_confirm": "Envoyer Perccent",
        "wallet_send_memo": "Mémo (facultatif)",
        "wallet_send_scan_body": "Pointez la caméra vers le QR de réception d'un autre utilisateur pour remplir son adresse PERC.",
        "wallet_send_scan_camera_error": "Impossible d'accéder à la caméra. Autorisez la caméra dans les réglages de l'appareil, puis réessayez.",
        "wallet_send_scan_cancel": "Annuler le scan",
        "wallet_send_scan_invalid": "Ce QR n'est pas une adresse PERC valide.",
        "wallet_send_scan_qr": "Scanner le QR code",
        "wallet_send_scan_ready": "Caméra prête — alignez le QR dans le cadre.",
        "wallet_send_scan_title": "Scanner une adresse PERC",
        "wallet_send_scan_unavailable": "Le scan QR nécessite une caméra de téléphone ou tablette (Android/iOS). Collez l'adresse PERC à la place.",
        "wallet_send_title": "Envoyer Perccent",
        "wallet_send_to": "Vers adresse PERC",
        "wallet_send_to_hint": "Collez ou scannez l'adresse PERC du destinataire",
        "wallet_session_expired": "Votre session portefeuille a expiré après 7 minutes sans connexion seed — reconnectez-vous pour lancer des analyses SCS.",
        "wallet_sidechain_height": "Hauteur microbloc side chain",
        "wallet_sidechain_id": "ID side chain",
        "wallet_sidechain_last_seal": "Dernier bloc de scellement",
        "wallet_sidechain_main_height": "Hauteur main-chain parente",
        "wallet_sidechain_parent": "Chaîne parente",
        "wallet_sidechain_pending": "Cycle de scellement : {completed} / {total} wards — {pending} / {bundle} microblocs dans le ward actif",
        "wallet_sign_in": "Se connecter",
        "wallet_signed_in_as": "Connecté en tant que {user}",
        "wallet_staking_earned": "Staking cumulé gagné : {amount} PERC",
        "wallet_staking_note": "Le PERC confirmé détenu rapporte 5 cent par bloc (10 % des 50 cent de base) après 1 confirmation de bloc. 1 PERC = 100 000 000 cent (0,00000001 PERC chacun).",
        "wallet_staking_title": "Staking cumulatif",
        "wallet_subtitle": "Chaîne Perccent · trésorerie pilotée par scénarios",
        "wallet_supply_infinite": "Offre continuum infinie (∞ PERC)",
        "wallet_sync_button": "Synchroniser le portefeuille",
        "wallet_sync_partial": "Synchronisation partielle — hauteur locale {local}, hauteur réseau {network}",
        "wallet_sync_seed_offline": "Impossible d'atteindre le nœud seed — vérifiez votre connexion internet et réessayez",
        "wallet_sync_success": "Portefeuille synchronisé avec le seed — hauteur de bloc {height}",
        "wallet_sync_syncing": "Synchronisation…",
        "wallet_time_confirmations_title": "Confirmations Chronoflux TIME",
        "wallet_title": "Evolve Wallet",
        "wallet_transactions_empty": "Lancez un calcul de probabilité % ou de cohésion sociale dans Analyse pour recevoir votre premier versement robinet Perccent.",
        "wallet_transactions_title": "TRANSACTIONS RÉCENTES",
        "wallet_treasury_cycle": "Cycle trésorerie n°{cycle}",
        "wallet_treasury_inflation_critical": "Trésorerie à 1 cent de réserve — renouvellement du pool au prochain scénario",
        "wallet_treasury_inflation_epoch": "Dernière époque d'inflation : {time}",
        "wallet_treasury_inflation_next": "Temps avant prochaine inflation : {wait}",
        "wallet_treasury_inflation_ready": "Inflation prête — lancez un scénario",
        "wallet_treasury_manual_send_note": "Trésorerie active — émission 0,00000001 PERC/min et versements robinet scénario continuent. Envois manuels depuis evolve_treasury désactivés.",
        "wallet_treasury_minted": "{minted} PERC émis ({pct}% continuum)",
        "wallet_treasury_note": "La chaîne Perccent avance sur l'analyse de scénarios — pas sur le construal Grok ni les frappes de champs. La trésorerie gagne 0,00000001 PERC par minute écoulée — offre continuum Chronoflux infinie. Le portefeuille trésorerie reste hors ligne jusqu'à ce qu'un utilisateur lance une analyse.",
        "wallet_treasury_offline_note": "La trésorerie attend le lancement de la blockchain. Lancez une analyse après le lancement pour puiser au robinet.",
        "wallet_treasury_pool": "Pool trésorerie (robinet) : {amount} PERC",
        "wallet_treasury_remaining": "Trésorerie restante : {amount} PERC",
        "wallet_treasury_send_locked": "Envois manuels depuis evolve_treasury désactivés. Émission et versements robinet continuent.",
        "wallet_treasury_setup_link": "Détenteur trésorerie ? Sécuriser le compte trésorerie",
        "wallet_treasury_setup_note": "Le détenteur de la trésorerie reçoit toutes les émissions pilotées par scénarios. Créez votre mot de passe maintenant (première utilisation uniquement).",
        "wallet_treasury_setup_title": "Sécuriser le compte trésorerie",
        "wallet_treasury_title": "Émission trésorerie",
        "wallet_treasury_username": "Nom d'utilisateur trésorerie",
        "wallet_tx_fee_burned": "Frais réseau brûlés",
        "wallet_tx_genesis": "Renouvellement genèse (283M PERC Perccent)",
        "wallet_tx_received": "Reçu de {user}",
        "wallet_tx_revert": "Transfert retourné",
        "wallet_tx_reward": "Récompense d'analyse",
        "wallet_tx_sent": "Envoyé à {user}",
        "wallet_tx_staking": "Récompense de staking",
        "wallet_tx_treasury": "Émission trésorerie",
        "wallet_username": "Nom d'utilisateur",
        "wallet_username_hint": "p. ex. parish_ward_42",
        "wallet_username_rules": "3–24 caractères : lettres minuscules, chiffres, underscores.",
        "ward_conclusion_link_button": "Voter sur cette conclusion dans Community Ward",
        "ward_conclusion_link_grok_badge": "Inclut le contexte construal Grok",
        "ward_conclusion_link_grok_note": "Construal Grok :",
        "ward_conclusion_link_loaded": "Chargé depuis la conclusion d'analyse Evolve",
        "ward_conclusion_link_question": "Question posée",
        "ward_conclusion_link_summary_header": "Analyse Evolve — résumé de proposition de ward",
        "ward_conclusion_link_vote_prefill_header": "Mon vote s'appuie sur cette analyse Evolve :",
        "ward_dual_populate_button": "Remplir les champs proposition et vote",
        "ward_dual_populated_from_link_ok": "Conclusion liée enrichie avec % et SCS — champs proposition et vote mis à jour.",
        "ward_dual_populated_ok": "Champs proposition et vote remplis avec % et SCS combinés.",
        "ward_dual_populator_from_link_note": "Via le lien de conclusion Evolve — exécute % et SCS pour ce scénario et remplit les champs proposition et vote avec les deux.",
        "ward_dual_populator_note": "Exécutez probabilité % et cohésion sociale ensemble, puis remplissez les champs proposition et vote avec les deux métriques.",
        "ward_dual_populator_title": "Analyse double — % et SCS",
        "ward_dual_rerun_from_link_button": "Relancer % + SCS pour le scénario lié",
        "ward_dual_run_button": "Lancer analyse % + SCS",
        "ward_dual_summary_header": "Analyse double Evolve — résumé de proposition de ward",
        "ward_dual_vote_prefill_header": "Mon vote s'appuie sur cette analyse Chronoflux double :",
        "ward_grok_available": "Construal Grok disponible pour l'analyse de ward",
        "ward_grok_heuristic_mode": "Construal Grok heuristique — leviers discursifs appliqués",
        "ward_grok_live_connected": "Grok en direct connecté — ω/σ/Iτ/Jμ remplis avant l'analyse",
        "ward_grok_use_construal": "Utiliser construal Grok",
        "ward_proposal_by": "Proposé par {user}",
        "ward_proposal_days_left": "{days} jour(s) restant(s) au listing",
        "ward_proposal_listed_ok": "Proposition listée pour tous les portefeuilles — vote ouvert 10 jours.",
        "ward_proposal_submit_button": "Lister 10 jours",
        "ward_proposal_submit_title": "Soumettre une proposition de ward",
        "ward_proposal_summary_label": "Résumé de la proposition",
        "ward_proposal_title_label": "Titre de la proposition",
        "ward_proposal_ward_label": "Ward communautaire",
        "ward_scenario_free_note": "Vérificateur ouvert uniquement — ne crédite pas de PERC. Utilisez l'onglet Analyse pour les récompenses robinet.",
        "ward_scenario_intro": "Vérificateur de probabilité de scénario ouvert gratuit — exécute probabilité % et score de cohésion sociale (SCS) du papier Chronoflux sans tirage trésorerie.",
        "ward_scenario_need_question": "Saisissez une question posée pour lancer le vérificateur.",
        "ward_scenario_percent_title": "Probabilité %",
        "ward_scenario_question_hint": "Quel résultat le ward doit-il peser ?",
        "ward_scenario_question_label": "Question posée",
        "ward_scenario_run": "Lancer vérification scénario ouvert",
        "ward_scenario_scs_title": "Score de cohésion sociale",
        "ward_scenario_topic_label": "Sujet de scénario (facultatif)",
        "ward_voting_abstain": "Abstention",
        "ward_voting_against": "Contre",
        "ward_voting_already_cast": "Ce portefeuille a voté — un vote par portefeuille et proposition.",
        "ward_voting_cast_ok": "Vote et commentaire enregistrés sur le registre ward.",
        "ward_voting_comment_choice_abstain": "Abstention",
        "ward_voting_comment_choice_against": "Contre",
        "ward_voting_comment_choice_for": "Pour",
        "ward_voting_comment_hint": "Expliquez comment l'analyse Chronoflux éclaire votre vote…",
        "ward_voting_comment_label": "Votre commentaire",
        "ward_voting_for": "Pour",
        "ward_voting_intro": "Soumettez une proposition visible par tous pendant 10 jours. Chaque portefeuille peut voter une fois par proposition.",
        "ward_voting_login_required": "Connectez-vous pour soumettre une proposition ou voter. Les résultats en direct ci-dessous sont publics — aucun vote requis pour les consulter.",
        "ward_voting_no_ballots_yet": "Pas encore de votes — les résultats apparaîtront ici au fur et à mesure.",
        "ward_voting_no_proposals": "Aucune proposition de ward ouverte pour le moment.",
        "ward_voting_public_comments": "Commentaires publics",
        "ward_voting_public_results_note": "Les décomptes et commentaires se mettent à jour pour chaque portefeuille à mesure que les bulletins sont émis.",
        "ward_voting_public_results_title": "Résultats publics en direct",
        "ward_voting_select_proposal": "Sélectionner une proposition",
        "ward_voting_tab_scenario": "Vérificateur de scénario",
        "ward_voting_tab_vote": "Vote",
        "ward_voting_total_ballots": "{count} portefeuille(s) ont voté",
        "ward_voting_vote_locked": "Vote enregistré pour ce portefeuille",
        "wallet_endpoint_label": "Point de terminaison : {endpoint}",
        "wallet_err_address_confidential": "Saisissez une adresse PERC confidentielle valide",
        "wallet_err_address_empty": "Saisissez une adresse PERC du destinataire",
        "wallet_err_address_invalid": "Saisissez une adresse PERC valide",
        "wallet_err_generic": "Une erreur s'est produite — réessayez",
        "wallet_err_insufficient_balance": (
            "Solde insuffisant — {total} {symbol} requis "
            "({amount} + {fee} de frais réseau)"
        ),
        "wallet_err_invalid_amount": (
            "Saisissez un montant {symbol} valide (jusqu'à 8 décimales)"
        ),
        "wallet_err_invalid_password": "Mot de passe incorrect",
        "wallet_err_minimum_send": "Envoi minimum : {min} {symbol} (1 cent)",
        "wallet_err_recipient_not_found": (
            "Adresse PERC du destinataire introuvable sur le réseau — le "
            "propriétaire doit s'inscrire et se connecter une fois pour que "
            "l'adresse soit détectable"
        ),
        "wallet_err_sign_in_to_send": "Connectez-vous pour envoyer {name}",
        "wallet_err_unknown_account": "Compte inconnu",
        "wallet_faucet_label_percent": "Analyse de probabilité %",
        "wallet_faucet_label_scs": "Analyse de cohésion sociale",
        "wallet_login_language_label": "Langue",
        "wallet_password_mismatch": "Les mots de passe ne correspondent pas",
        "wallet_inbound_revert_days": "7 jours",
        "wallet_inbound_revert_hours": "plusieurs heures",
        "wallet_inbound_revert_seconds": "un court délai",
        "wallet_status_account_created": "Compte créé",
        "wallet_status_faucet_credited": "+{amount} {symbol}",
        "wallet_status_genesis_renewal": (
            "Bloc genèse — cycle trésorerie {cycle} renouvelé "
            "(283M {symbol} {name})"
        ),
        "wallet_status_sent_instant": (
            "Envoyé {amount} {symbol} à {dest} "
            "(frais réseau {fee} {symbol})"
        ),
        "wallet_status_sent_queued": (
            "Envoyé {amount} {symbol} à {dest} "
            "(frais réseau {fee} {symbol}) — en file jusqu'à connexion sur "
            "le réseau sous {delay}, sinon retour vers votre portefeuille"
        ),
        "wallet_status_signed_in": "Connecté en tant que {user}",
        "wallet_status_treasury_cap": "Plafond de trésorerie atteint",
        "wallet_status_treasury_empty": (
            "Trésorerie vide — relancez un scénario plus tard"
        ),
        "wallet_status_treasury_secured": (
            "Trésorerie sécurisée — en attente de la connexion trésorerie "
            "seed pour lancer la chaîne"
        ),
        "wallet_tx_microblock_seal": "Scellement microbloc Chronoflux",
    }


WALLET_LANG_BUILDERS = {
    "fr": _fr,
}